version: "3" #파일 규격 버전
services: # 이 항목 밑에 실행하려는 컨테이너 들을 정의 
  sc-table-db: # 서비스명
    restart: always
    image: mysql # 사용할 이미지
    container_name : sc-table-mysql # 컨테이너 이름 설정
    ports : 
      - "3306:3306" # 접근 포트 설정 ( 컨테이너 외부:컨테이너 내부)
    environment: # -e 옵션
     -  MYSQL_DATABASE=SC_TABLE
     -  MYSQL_ROOT_PASSWORD=123 # MYSQL 패스워드 설정 옵

    command : # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci 
      - --default-authentication-plugin=mysql_native_password
    volumes:
      - ./.data:/var/lib/mysql  # -v 옵션 (디렉토리 마운트 설정)
volumes:
  sc-table-db:
